### ISSUE TITLE
[2020-08-20]: [VWS/Covid19NotificationApp] "CoronaMelder is niet actief, bekijk uw instellingen"

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-ios#38] opened 2020-08-20 07:18 UTC
### Describe the bug, issue or concern

I received an alert yesterday that my CoronaMelder was not active and i should check the settings.
My parents and a colleague also received the warning. 

### To Reproduce
Nothing, alert is suddenly shown.

### Expected behavior
I expect the CoronaMelder to stay active.

### Screenshots
Unfortunately i was unable to make a screenshot this time.
iPhone 11 with 13.6.1
iPhone SE1 with 13.6.1
iPhone X with 14b4

### Additional context
- 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment] 2020-08-24 07:25
Duplicate of #37. Once background processing works this will be resolved.

**Closed by rvandijke** 2020-08-24 07:25 UTC
