### ISSUE TITLE
[2020-08-23]: [VWS/Covid19NotificationApp] Exposure checks not working on iOS 14

### ISSUE THREAD

**Issue by erikvdwal** [minvws/nl-covid19-notification-app-ios#40] opened 2020-08-23 18:54 UTC
### Describe the bug, issue or concern

I installed the CoronaMelder app the day it was released. The exposure log has remained empty since, despite the fact that numerous keys have been published since. Because I'm running iOS 14 beta 5, I assumed it might be an issue with the beta rather than the app.

In an attempt to confirm this, I installed the Corona-Warn app (Germany) and switched regions. After about 24 hours, entries did start appearing in the exposure log, which makes me think this is an issue specific to the CoronaMelder app.

Edit: Note that this doesn't just affect the app when it's running in the background like #37. When the app is foregrounded or restarted completely and kept running in the foreground for a while, the exposure log still remains empty.

### To Reproduce
1. Install iOS 14 beta 5
2. Install CoronaMelder
3. Run the app for an extended period (e.g. 24 hours)
4. Go the Settings → Exposure Notification → Exposure Logging Status → Exposure checks
5. Confirm that the exposure log remains empty

### Expected behavior
Given that [there are numerous publications](https://corona-melder-keyset-dashboard.netlify.app) and multiple update windows of 4 hours (?) have passed, I would expect the exposure log to contain entries.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14 beta 5

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment] 2020-08-24 07:18
Duplicate of #37. We are aware that background processing is not working correctly at all times.

**Comment by erikvdwal** [comment] 2020-08-24 09:37
> Duplicate of #37. We are aware that background processing is not working correctly at all times.

It appears I forgot to mention this in the ticket, but contrary to #37, processing also isn't working when the app is running in the foreground, even after killing/restarting the app and keeping it running in the foreground for a while, so this may still be a separate issue.

**Comment by rvandijke** [comment] 2020-08-24 10:53
Thanks for clarifying. I did launch CoronaMelder on iOS 14 beta 5 and I did see the framework returning 'notAuthorised' even while I did authorise. I don't have much time today to look into iOS 14 specifics, but we will ensure that when iOS 14 goes live (out of beta) we have a compatible and working version of CoronaMelder. This week iOS 14 testing should start so we have time to raise any issues to Apple.

**Comment by ijansch** [comment] 2020-08-27 06:48
On slack there was a report of b6 now working so could be fixed on Apple side. https://codefornl.slack.com/archives/C011R4NCFMJ/p1598435361061200?thread_ts=1597858545.178200&channel=C011R4NCFMJ&message_ts=1598435361.061200

**Comment by erikvdwal** [comment] 2020-08-27 08:58
After installing iOS 14 beta 6 I also see the log being populated, at least when the app is launched. I have not yet seen any background checks resulting in log entries. The 'Provided Key Count' row also seems to be missing from each entry, so I cannot confirm that keys are actually being provided, though Apple may have just decided to remove that piece of info.

**Comment by erikvdwal** [comment] 2020-08-29 09:14
Small update: I now also see a couple of log entries that were generated while the app was running in the background, but as noted in a comment on #37, those checks only ran while the device was charging.

**Comment by hmeerlo** [comment] 2020-09-03 12:09
For me the app does perform regular background checks (beta 6) but I looked at the exposure log and has not once checked against any Files. The Files array in the exposure log is empty for all the checks it has done.

**Comment by roelspruit** [comment] 2020-11-09 09:52
I'm going to close this issue since we have not encountered any issues specific to iOS 14 recently. We'll make sure to keep monitoring iOS updates to make sure this keeps working in the future

**Closed by roelspruit** 2020-11-09 09:52 UTC
