### ISSUE TITLE
Bug: Bottom section on setup panels unreadable

### ISSUE THREAD

**Issue by fvdm** [minvws/nl-covid19-notification-app-ios#51] opened 2020-10-09 15:39 UTC
### Describe the bug, issue or concern

Some of the information, during the setup panels, is unreadable because the text reached the end of the view. As the panel can't scroll you cannot reach the lower text.

This happens on the 'Zet CoronaMelder aan' step and the last one about sharing the app with others.

### To Reproduce

1. Install the app from the App Store as new on an iPhone 8.
2. Go through the onboarding.
3. Eventually you get panels where the bottom text continues outside the view.
4. Try to scroll the text up, but it doesn't respond.

### Expected behavior
The text area can scroll. When you intuitively swipe up the lower text becomes visible.

### Screenshots
![image](https://user-images.githubusercontent.com/93784/95601889-70be9180-0a54-11eb-9f75-38a948c38f69.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.0.1
 - Browser: CoronaMelder app
 - Version: 1.0.10

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment] 2020-10-09 15:54
Interesting. I can't reproduce this on my iPhone 8 simulator. The text fits there. Do you have an increased font size setting enabled on your phone? In any case this should work for people with that settings enabled so I'll make an issue in our internal system for this. (ticket nr. 58917)

**Comment by fvdm** [comment] 2020-10-09 16:35
@roelspruit Yes, I have font size on +1 from the standard size.

I should add that scrolling works on some panels but not all.

**Comment by roelspruit** [comment] 2020-10-09 16:37
@fvdm Thanks for the report. I just fixed the issue so it should make it into the next release of the app.

**Comment by roelspruit** [comment] 2020-11-06 16:04
This is fixed in the latest release of the app so I'm closing this issue.

**Closed by roelspruit** 2020-11-06 16:04 UTC
Labels: mirrored-to-azure
