### ISSUE TITLE
X button does not work...

### ISSUE THREAD

**Issue by SemPruijs** [minvws/nl-covid19-notification-app-ios#33] opened 2020-08-18 14:17 UTC
# X button does not work

**Open the "CoronaMelder" app.**
**Select the "Invite others to the app" button. See screenshot:**
![IMG_1281](https://user-images.githubusercontent.com/19208988/90521049-5bbb3580-e16a-11ea-8e5c-ff102139df4c.jpeg)

**Click on the "Share app" button**
**Select "Mesages" See screenshot:**
![IMG_015269496BA9-1](https://user-images.githubusercontent.com/19208988/90521861-4e527b00-e16b-11ea-842b-0679c5f86803.jpeg)
**Click on cancel in the upper left corner. See screen shot:**
![IMG_1283](https://user-images.githubusercontent.com/19208988/90522216-bc973d80-e16b-11ea-9195-08da3746bcce.jpeg)

**Click on the X in the left corner on the share window. See screen shot**
![IMG_1284](https://user-images.githubusercontent.com/19208988/90522563-27487900-e16c-11ea-8784-1b0922356607.jpeg)

## And now the bug

When you click on the X button, the window will not close. You have to do the swipe down gesture to exit the screen. I expected that this would close the window.

Thank you for reading this and taking this in consideration 😄

### Smartphone
 - Device: iPhone 7
 - OS: iOS 13.6
 - Version: (From the App Store) 1.0.3

**Comment by edwardmp** [comment] 2020-08-18 16:55
Can reproduce on 1.0.3 (app store).

The issue only seems to be prevalent when you have actually selected an app to share the message with, otherwise the X button works fine. Also, even when the X button doesn't work, you can still dismiss the modal by swiping down though.

**Comment by edwardmp** [comment] 2020-08-18 17:16
Seems like this was fixed by #31 already

**Comment by sbarow** [comment] 2020-08-19 07:09
@edwardmp yup this should be fixed now. You can update the app via the App Store to version 1.0.4 and confirm it is fixed.

**Comment by SemPruijs** [comment] 2020-08-19 11:14
yesss, the bug is fixed in the update. Thank you 😁

**Closed** 2020-08-19 11:15 UTC
